name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{secrets.SSH_KEY}}" > `/.ssh/deploy_kep.pem
          chmod 600 ~/.ssh/deploy_key.pem
        shell: bash

      - name: Deploying to server
        env:
          NODE_ENV: production
        run: |
          ssh -i ~/.ssh/deploy_kep.pem `${{secrets.SSH_USER}}@${{secrets.SERVER_DNS}}` << 'EOF'
            cd /home/ubuntu
            git pull origin main
            npm install --production
            pm2 restart all || pm2 start server.js --name "health-flow-backend" \
            -e MONGO_URI=`${{secrets.MONGO_URI}}` \
            -e FRONTEND_URL=`${{secrets.FRONTEND_URL}}` \
            -e DASHBOARD_URL=`${{secrets.DASHBOARD_URL}}` \
            -e JWT_SECRET_KEY=`${{secrets.JWT_SECRET_KEY}}` \
            -e JWT_EXPRESS=`${{secrets.JWT_EXPIRES}}` \
            -e COOKIES_EXPIRES=`${{secrets.COOKIE_EXPIRE}}` \
            -e CLOUDINARY_CLOUD_NAME=`${{secrets.CLOUDINARY_CLOUD_NAME}}` \
            -e CLOUDINARY_API_SECRET=`${{secrets.CLOUDINARY_API_SECRET}}` \
            -e CLOUDINARY_API_KEY=`${{secrets.CLOUDINARY_API_KEY}}` \
            EOF
