name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd /home/ubuntu/actions-runner-backend
          git pull origin main
          npm install --production

      - name: Start or Restart the app
        env:
          NODE_ENV: production
        run: |
          pm2 restart all || pm2 start server.js --name "health-flow-backend" \
          -e MONGO_URI=`${{secrets.MONGO_URI}}` \
          -e FRONTEND_URL=`${{secrets.FRONTEND_URL}}` \
          -e DASHBOARD_URL=`${{secrets.DASHBOARD_URL}}` \
          -e JWT_SECRET_KEY=`${{secrets.JWT_SECRET_KEY}}` \
          -e JWT_EXPRESS=`${{secrets.JWT_EXPIRES}}` \
          -e COOKIES_EXPIRES=`${{secrets.COOKIE_EXPIRE}}` \
          -e CLOUDINARY_CLOUD_NAME=`${{secrets.CLOUDINARY_CLOUD_NAME}}` \
          -e CLOUDINARY_API_SECRET=`${{secrets.CLOUDINARY_API_SECRET}}` \
          -e CLOUDINARY_API_KEY=`${{secrets.CLOUDINARY_API_KEY}}` \
